spark.master local[2]
spark.driver.memory 1g
spark.ui.enabled false
spark.sql.shuffle.partitions 4
spark.sql.warehouse.dir file:///warehouse
spark.sql.hive.metastore.version 4.1.0
spark.sql.hive.metastore.jars path
spark.sql.hive.metastore.jars.path file:///opt/hive-client/lib/*,file:///opt/hive-client/hadoop/common/*,file:///opt/hive-client/hadoop/common/lib/*,file:///opt/hive-client/hadoop/mapreduce/*,file:///opt/hive-client/hadoop/hdfs/*,file:///opt/hive-client/hadoop/hdfs/lib/*
spark.hadoop.hive.metastore.uris thrift://metastore:9083
spark.sql.timestampType TIMESTAMP_NTZ
